	.align 2
gText_ConfirmSave::
	.string " $"

gText_AlreadySavedFile::
	.string " $"

gText_SavingDontTurnOff::
	.string "Hehe…$"

gText_SavingDontTurnOff23::
	.string "We will save your progress…$"

gText_PlayerSavedGame::
	.string "Have fun! - Trick Room Guy$"

gText_DifferentSaveFile::
	.string " $"

gText_SaveError::
	.string "Save error.$"

gText_SavingDontTurnOffPower::
	.string "Hehe…$"
	

gText_PlayerSavedGame2::
	.string "Saving Finished.$"
